const sheets = require('../config/googleSheetsClient');
const supabase = require('../config/supabaseClient');
const bcrypt = require('bcryptjs');
const nodemailer = require('nodemailer');
const { jobStatus: expiryStatus } = require('../jobs/expiryJob');
const { jobStatus: reminderStatus } = require('../jobs/reminderJob');
const { appendUserToSheet } = require('../utils/sheetsSync');

const SPREADSHEET_ID = process.env.GOOGLE_SHEET_ID;

const getAdminUsers = async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('users')
      .select('id, name, email, role, department, created_at')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Supabase error fetching users:', error);
      return res.status(500).json({ error: 'Failed to fetch users from database' });
    }

    res.status(200).json(data || []);
  } catch (err) {
    console.error('Error fetching admin users:', err);
    res.status(500).json({ error: 'Failed to fetch users' });
  }
};

const getAdminOffers = async (req, res) => {
  try {
    // Fetch all offers from Supabase directly
    const { data, error } = await supabase
      .from('offers')
      .select('*, users!generated_by(email, name), rejections(*)')
      .order('created_at', { ascending: false });

    if (error) throw error;
      
    res.status(200).json(data || []);
  } catch (error) {
    console.error('Error fetching admin offers:', error);
    res.status(500).json({ error: 'Failed to fetch offers' });
  }
};

const updateUserRole = async (req, res) => {
  try {
    const { email } = req.params;
    const { role } = req.body;

    if (!['hr', 'manager', 'admin'].includes(role)) {
      return res.status(400).json({ error: 'Invalid role provided' });
    }

    const { error } = await supabase
      .from('users')
      .update({ role })
      .eq('email', email);

    if (error) {
      console.error('Supabase update error:', error);
      return res.status(500).json({ error: 'Failed to update user role' });
    }

    // Sheets sync skipped — Google Sheets integration currently unavailable
    res.status(200).json({ message: 'User role updated successfully' });
  } catch (err) {
    console.error('Error updating user role:', err);
    res.status(500).json({ error: 'Failed to update user role' });
  }
};

const deleteUser = async (req, res) => {
  try {
    const { email } = req.params;

    // Step 1: Get user ID from email
    const { data: user, error: findError } = await supabase
      .from('users')
      .select('id')
      .eq('email', email)
      .single();

    if (findError || !user) {
      return res.status(404).json({ error: 'User not found' });
    }

    // Step 2: Nullify offers generated by this user (preserve offer records)
    const { error: offersError } = await supabase
      .from('offers')
      .update({ generated_by: null })
      .eq('generated_by', user.id);

    if (offersError) {
      console.error('Failed to nullify offers:', offersError);
      return res.status(500).json({ error: 'Failed to unlink user offers before deletion' });
    }

    // Step 3: Delete the user
    const { error: deleteError } = await supabase
      .from('users')
      .delete()
      .eq('id', user.id);

    if (deleteError) {
      console.error('Supabase delete error:', deleteError);
      return res.status(500).json({ error: 'Failed to delete user' });
    }

    res.status(200).json({ message: 'User deleted successfully' });
  } catch (err) {
    console.error('Error deleting user:', err);
    res.status(500).json({ error: 'Failed to delete user' });
  }
};

const createUser = async (req, res) => {
  try {
    const { name, email, password, role, department } = req.body;
    
    if (!name || !email || !password || !role) {
      return res.status(400).json({ error: 'Name, email, password, and role are required' });
    }

    if (role === 'manager' && !department) {
      return res.status(400).json({ error: 'Department is required for managers' });
    }

    const { data: existingUser } = await supabase
      .from('users')
      .select('id')
      .eq('email', email)
      .single();

    if (existingUser) {
      return res.status(400).json({ error: 'User already exists' });
    }

    const salt = await bcrypt.genSalt(10);
    const passwordHash = await bcrypt.hash(password, salt);

    const { data: newUser, error: insertError } = await supabase
      .from('users')
      .insert([{
        name,
        email,
        password_hash: passwordHash,
        role,
        department: role === 'manager' ? department : null
      }])
      .select()
      .single();

    if (insertError) throw insertError;

    // Async sync to Google Sheets
    appendUserToSheet(newUser).catch(err => console.error('Failed to append user to sheet:', err));

    res.status(201).json({ message: 'User created successfully', user: { id: newUser.id, email, name, role } });
  } catch (error) {
    console.error('Error creating user:', error);
    res.status(500).json({ error: 'Failed to create user' });
  }
};

const getSystemHealth = async (req, res) => {
  // Check Google Sheets
  let sheetsConnected = false;
  try {
    await sheets.spreadsheets.get({ spreadsheetId: SPREADSHEET_ID });
    sheetsConnected = true;
  } catch (err) {
    console.error('Sheets health check failed:', err.message);
  }

  // Email check — SMTP verify blocks/crashes on Render free tier
  // Use presence of RESEND_API_KEY as the indicator instead
  const smtpConnected = !!process.env.RESEND_API_KEY;

  // Always return 200 — never let health check crash
  return res.status(200).json({
    googleSheets: sheetsConnected ? 'ok' : 'error',
    smtp: smtpConnected ? 'ok' : 'error',
    cronExpiry: expiryStatus.lastRun || null,
    cronReminder: reminderStatus.lastRun || null,
  });
};

module.exports = {
  getAdminUsers,
  getAdminOffers,
  updateUserRole,
  deleteUser,
  createUser,
  getSystemHealth
};
